---
# tasks file for vps
- name: Install podman
  ansible.builtin.package:
    name: podman
    state: latest

# While the following bug from the podman module is not solved, I can't 
# mount volumes with SELinux in Enforcing mode.
# https://github.com/containers/ansible-podman-collections/issues/102
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: create http front podman network
  containers.podman.podman_network:
    name: http_front
    internal: true
    ip_range: 10.13.38.0/25
    subnet: 10.13.38.0/24
    gateway: 10.13.38.1

- name: create podman base volumes directory
  ansible.builtin.file:
    path: "{{ container_volumes_base_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root
    force: yes

- name: create podman volumes directories
  ansible.builtin.file:
    path: "{{ container_volumes_base_dir }}/{{ item.0.name }}/{{ item.1 }}"
    state: directory
    mode: 0755
    owner: root
    group: root
    force: yes
  loop: "{{ containers|zip(volume_directory)|list }}"

- name: Run containers list
  containers.podman.podman_container:
    name: "{{ item.name }}"
    image: "{{ item.image }}"
    state: started
    ip: "{{ item.ip }}"
    recreate: "{{ item.recreate }}"
    #subuidname: nils
    #subgidname: nils
    ports: "{{ item.ports | default([\"\"]) }}"
    volume: "{{ item.volume }}"
    generate_systemd:
      path: /etc/systemd/system/
      restart_policy: always
      names: true
      container_prefix: container
    #notify: start nginx_site1
  loop: "{{ containers }}"

- name: Enable container services
  ansible.builtin.systemd:
    name: "container-{{ item.name }}"
    daemon_reload: yes
    enabled: yes
  loop: "{{ containers }}"

