---
# tasks file for vps
- name: Install podman
  tags:
    - podman
  ansible.builtin.package:
    name: podman

# While the following bug from the podman module is not solved, I can't
# mount volumes with SELinux in Enforcing mode.
# https://github.com/containers/ansible-podman-collections/issues/102
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  tags:
    - selinux
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: Create http front podman network
  tags:
    - podman
  containers.podman.podman_network:
    name: http_front
    internal: true
    ip_range: 10.13.38.0/25
    subnet: 10.13.38.0/24
    gateway: 10.13.38.1

- name: Create podman base volumes directory
  tags:
    - podman
  ansible.builtin.file:
    path: "{{ container_volumes_base_dir }}"
    state: directory
    mode: 0755
    owner: root
    group: root
    force: true

- name: Create podman volumes directories
  tags:
    - podman
    - mkdir
  ansible.builtin.file:
    path: "{{ item.1.host }}"
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: true
  loop: "{{ containers | subelements('volume') }}"
  loop_control:
    label: "{{ item.0.name }} - {{ item.1.host }}"

- name: Sync configurations
  tags:
    - config
    - sync
  ansible.posix.synchronize:
    src: "templates/{{ item.name }}/"
    dest: "{{ container_volumes_base_dir }}/{{ item.name }}/conf/"
    delete: true
    recursive: true
    links: true
    rsync_opts:
      - "--exclude=*~"
  loop: "{{ containers }}"
  when: "item.sync == true"
  loop_control:
    label: "{{ item.name }}"

- name: Run containers list
  tags:
    - podman
  containers.podman.podman_container:
    name: "{{ item.0.name }}"
    image: "{{ item.0.image }}"
    state: started
    ip: "{{ item.0.ip }}"
    recreate: "{{ item.0.recreate }}"
    # subuidname: nils
    # subgidname: nils
    ports: "{{ item.0.ports | default([\"\"]) }}"
    # volume: "{{ item.volume }}"
    volume: "{{ item.1.host }}:{{ item.1.pod }}"
    generate_systemd:
      path: /etc/systemd/system/
      restart_policy: always
      names: true
      container_prefix: container
      # notify: start nginx_site1
  # loop: "{{ containers }}"
  loop: "{{ containers | subelements('volume') }}"

- name: Enable container services
  tags:
    - podman
    - systemd
  ansible.builtin.systemd:
    name: "container-{{ item.name }}"
    daemon_reload: true
    enabled: true
  loop: "{{ containers }}"
