---
# handlers file for vps

- name: start reverse_proxy
  service:
    name: container-reverse_proxy
    state: started

- name: start nginx_site1
  service:
    name: container-nginx_site1
    state: started

- name: start nginx_site2
  service:
    name: container-nginx_site2
    state: started
