---
# vars file for vps
container_volumes_base_dir: /srv/containers

volume_directory:
  - "conf"
  - "docroot"
  - "log"

containers:
  - name: site1
    image: docker.io/library/nginx
    ip: 10.88.80.1
    recreate: true
    sync: true
    volume:
      - host: "{{ container_volumes_base_dir }}/site1/docroot"
        pod: "/usr/share/nginx/html"
      - host: "{{ container_volumes_base_dir }}/site1/log"
        pod: "/var/log/nginx"
      - host: "{{ container_volumes_base_dir }}/site1/conf/nginx"
        pod: "/etc/nginx"
  - name: site2
    image: docker.io/library/nginx
    ip: 10.88.80.2
    recreate: true
    sync: true
    volume:
      - host: "{{ container_volumes_base_dir }}/site2/docroot"
        pod: "/usr/share/nginx/html"
      - host: "{{ container_volumes_base_dir }}/site2/log"
        pod: "/var/log/nginx"
      - host: "{{ container_volumes_base_dir }}/site2/conf/nginx"
        pod: "/etc/nginx"
  - name: reverse_proxy
    image: docker.io/library/nginx
    ip: 10.88.80.254
    recreate: true
    sync: true
    ports:
      - "80:80"
      - "443:443"
    volume:
      - host: "{{ container_volumes_base_dir }}/reverse_proxy/docroot"
        pod: "/usr/share/nginx/html"
      - host: "{{ container_volumes_base_dir }}/reverse_proxy/log"
        pod: "/var/log/nginx"
      - host: "{{ container_volumes_base_dir }}/reverse_proxy/conf/nginx"
        pod: "/etc/nginx"
  - name: pihole
    image: docker.io/pihole/pihole
    ip: 10.88.80.3
    recreate: true
    sync: false
    # this port exposition is just for diag purposes
    # don't let this go to prod !
    ports:
      - "8053:80"
    volume:
      - host: "/srv/containers/pihole/conf/pihole/"
        pod: "/etc/pihole"
      - host: "/srv/containers/pihole/conf/dnsmasq/"
        pod: "/etc/dnsmasq.d"
      - host: "/srv/containers/pihole/log/"
        pod: "/srv/log"
